### ISSUE TITLE
Mouse doesn't go to tap position

### ISSUE THREAD

**Issue by ZRupp** [rock88/moonlight-nx#11]
The mouse does not go to the tap position, but instead goes to an area far to the right of the tap position.

**Comment by ZRupp** [comment]
Ok, so I just tested it again with my second monitor disabled and now the mouse clicks on the tap position.

**Comment by cgutman** [comment]
Yeah, this is a problem with GeForce Experience not properly handling multiple monitors on the host.

https://github.com/moonlight-stream/moonlight-android/issues/821

**Comment by ZRupp** [comment]
Ah bummer. I'll just disable my second monitor when using this, then.
