### ISSUE TITLE
SSL error after compiling manually

### ISSUE THREAD

**Issue by masagrator** [rock88/moonlight-nx#12]
By using release apps I don't have this issue.
But after compiling it manually I have SSL error in moonlight after writing 0000 code to Geforce Experience.

I have everything up-to-date, using WSL Ubuntu.

In your readme it stays that I need to use curl 7.69.1, but there is no info if updating from 7.69.1-1 to 7.69.1-2 can break things (theoretically it's still 7.69.1).

And btw. update readme, because makefile pointer shows CFLAGS, not LIBS. ;)

**Comment by rock88** [comment]
Yep, latest curl 7.69.1-2 not working properly (7.69.1-2 has a big changes for use SSL from libnx, not from mbedTLS), README has link to curl PKGBUILD 7.69.1-1, only this version works fine.

You can view how build properly curl [here](https://github.com/rock88/moonlight-nx/blob/master/.github/workflows/build.yml#L27).

Also I'll update README for more describe about curl version and how it install.

**Comment by rock88** [comment]
I updated build instructions in README. Maybe later I try to libcurl 7.69.1-2 will work, or add scripts for build libcurl 7.69.1-1 in project `lib` directory, for not overwrite currently installed libcurl.
