### ISSUE TITLE
Add option to ignore unsupported resolutions

### ISSUE THREAD

**Issue by KiralyCraft** [rock88/moonlight-nx#13]
Linked comment: https://github.com/loki-47-6F-64/sunshine/issues/23#issuecomment-644304679

**Comment by rock88** [comment]
I added this option to Settings, can you check [this](https://github.com/rock88/moonlight-nx/actions/runs/144624787) build?

**Comment by KiralyCraft** [comment]
Yep, it works wonders. Thank you, much appreciated
