### ISSUE TITLE
Any game I try to open displays "Invalid"

### ISSUE THREAD

**Issue by IgnacioAlme** [rock88/moonlight-nx#18]
Doesn't matter what game it is, or what plataform is in (Epic, Steam, Origin), games won't run despite being displayed in the applications list. Tries to start them only to end up displaying "error Invalid".

**Comment by cgutman** [comment]
This broken error message from GeForce Experience means that the Nvidia Virtual Audio device is missing or unusable. If you have RTX Voice installed, remove that first as it can interfere with GameStream. If not, reinstall GeForce Experience.

**Comment by IgnacioAlme** [comment]
Tried both things, didn't work.

**Comment by IgnacioAlme** [comment]
Checking the option to reproduce audio on PC made it work.
