### ISSUE TITLE
Mapping buttons for Xbox layout is not working

### ISSUE THREAD

**Issue by PabloZaiden** [rock88/moonlight-nx#21]
I've mapped the buttons to have an "XBox-like" layout:
```
   Y
X     B
   A
```

While the button-mapping screen shows it propertly, when opening a game it's still using the Switch button layout:
```
   X
Y     A
   B
```

Am I missing something, or is it currently broken?

**Comment by PabloZaiden** [comment]
It actually seem to work but only if setting the controls per game, and not in general

**Comment by rock88** [comment]
Sorry for delay... Yep, if you once opened global gamepad settings this settings will be applying for all games. So needs select game with dpad and press Y button for remap buttons for this game. Or you can just remove `gamepad_mapping.json` file from sdcard/switch/moonlight directory.

**Comment by PabloZaiden** [comment]
The issue is that when I've applied the global mappings, those weren't working. It only started working when I mapped a specific game.

**Comment by PabloZaiden** [comment]
Any plan on making a new release including the commits after the last release? Mostly for the default ab xy swaps.

**Comment by dantesvictus** [comment]
Wow the man PabloZaiden himself..

**Comment by spitfire** [comment]
@rock88 any plans for a new release? This could really come in handy.

**Comment by rock88** [comment]
@spitfire I found few freezes and try to fix it, but you always can grab latest builds from [here](https://github.com/rock88/moonlight-nx/actions) =)

**Comment by spitfire** [comment]
> @spitfire I found few freezes and try to fix it, but you always can grab latest builds from [here](https://github.com/rock88/moonlight-nx/actions) =)

Thanks, didn't know you had workflow for autobuilds :)

**Comment by spitfire** [comment]
> > @spitfire I found few freezes and try to fix it, but you always can grab latest builds from [here](https://github.com/rock88/moonlight-nx/actions) =)
> 
> Thanks, didn't know you had workflow for autobuilds :)

For some reason all artifacts give me 404:/

**Comment by rock88** [comment]
Done in [release 1.2.0](https://github.com/rock88/moonlight-nx/releases/tag/1.2.0)
