### ISSUE TITLE
Sort gamelist in alphabetical order

### ISSUE THREAD

**Issue by chrisipa** [rock88/moonlight-nx#23]
Hello @rock88, 

first of all thanks a lot for your great work on this Moonlight streaming client for the Nintendo Switch. Works really great so far.

One minor problem is the order in which the gamelist is sorted. I'm not sure after which criteria the sorting is done (title ID?) but it is a little bit confusing to me and probably also for other users.

**I think it would be best to use the same alphabetical order as the other Moonlight clients (e.g. for Android) do.**

Best regards
Chris

**Comment by rock88** [comment]
Done, will be available in the next release 🎉

**Comment by chrisipa** [comment]
I tried the newest build of the nro file and the game list is now sorted correctly. Thanks a lot for this change. 

My main problem is, that I cannot use the newset build due to stability problems. I always get the error message **Bad Connection**, no matter which settings I try.

When do you plan to release a new stable version?

Thanks again for your great work.

**Comment by rock88** [comment]
Done in [release 1.2.0](https://github.com/rock88/moonlight-nx/releases/tag/1.2.0)

**Comment by chrisipa** [comment]
I can confirm that this issue has been fixed with release 1.2.0. Thanks again for your great work @rock88
