### ISSUE TITLE
Optimize UI layout for game list in docked mode

### ISSUE THREAD

**Issue by chrisipa** [rock88/moonlight-nx#27]
Hi @rock88,

when using the Moonlight client in handheld mode (720p) everything is rendered fine. 

The problem is that if you dock your switch and use a higher resolution (1080p) the game list is not rendered full screen:

![2020081807395500-8B9069CD8189A17366EB861AADF9A092](https://user-images.githubusercontent.com/7666084/90474452-977fdc00-e125-11ea-8651-50e33b2749c1.jpg)

Is there any way to improve the UI layout of the game list to use the full screen for the box arts?

Best regards
Chris

**Comment by rock88** [comment]
Hi! Ohhh, I checked it for a long time ago and everything was fine (UI layout has adaptation for screen size changed), but currently some broke, will research what wrong.

**Comment by rock88** [comment]
Done, will be available in the next release 🎉

**Comment by rock88** [comment]
Done in [release 1.2.0](https://github.com/rock88/moonlight-nx/releases/tag/1.2.0)

**Comment by chrisipa** [comment]
I can confirm that this issue has been fixed with release 1.2.0. Thanks again for your great work @rock88
