### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by funregis** [rock88/moonlight-nx#3]
hi, I launch moonlight (1.0.9) with title redirection, the big picture is launching, but when I click on a game, It shows a popup with : unknown error.

with my phone I use moonlight android and it's working well.

**Comment by rock88** [comment]
Hi, you can enable `Write debug log` feature in settings, catch this error and inspect log.txt at sdcard/switch/moonlight or attach this file here.

**Comment by funregis** [comment]
here is the log : 

2020-04-00 22:16:51 [INFO][CURL] Request:
https://10.1.14.88:47984/serverinfo?uniqueid=0123456789ABCDEF
2020-04-00 22:16:52 [INFO][CURL] Response:
<?xml version="1.0" encoding="UTF-16"?><root protocol_version="0.1" query="serverinfo" status_code="200" status_message="OK"><AuthenticationType>1</AuthenticationType><ConnectionState></ConnectionState><CurrentClient>0</CurrentClient><GfeVersion>3.20.3.63</GfeVersion><GsVersion>gs_04_22_28196077</GsVersion><HttpsPort>47984</HttpsPort><LocalIP>10.1.14.88</LocalIP><LocalIPs><Address>10.1.14.88</Address></LocalIPs><LoginState>2</LoginState><MaxLumaPixelsH264>1721324928</MaxLumaPixelsH264><MaxLumaPixelsHEVC>1869449984</MaxLumaPixelsHEVC><Mode>0</Mode><PairStatus>1</PairStatus><ServerCapability>3895</ServerCapability><ServerCodecModeSupport>3843</ServerCodecModeSupport><ServerColorSpaceSupport>2</ServerColorSpaceSupport><SupportedDisplayMode><DisplayMode><Height>2160</Height><RefreshRate>60</RefreshRate><Width>3840</Width></DisplayMode><DisplayMode><Height>2160</Height><RefreshRate>30</RefreshRate><Width>3840</Width></DisplayMode><DisplayMode><Height>1080</Height><RefreshRate>30</RefreshRate><Width>1920</Width></DisplayMode><DisplayMode><Height>720</Height><RefreshRate>30</RefreshRate><Width>1280</Width></DisplayMode></SupportedDisplayMode><accountId>0A2357BA21F9FA2784BD7EDCA87CA0F35F4B25237483DC609BAB4190AABCB447</accountId><appversion>7.1.422.0</appversion><currentgame>0</currentgame><gamelistid>66082427b583fc7294d025914498d3b6</gamelistid><gputype>GeForce RTX 2080</gputype><hostname>PC-REGIS</hostname><mac>00:D8:61:53:00:8F</mac><numofapps>0</numofapps><resyncSuccessful>0</resyncSuccessful><state>MJOLNIR_STATE_SERVER_AVAILABLE</state><uniqueid>3dea3d5b-3c1f-4986-9854-e5c9762321dc</uniqueid></root>
2020-04-00 22:16:53 [INFO][CURL] Request:
https://10.1.14.88:47984/applist?uniqueid=0123456789ABCDEF
2020-04-00 22:16:53 [INFO][CURL] Response: Ok
2020-04-00 22:17:03 [ERROR][MOONLIGHTSESSION] Failed to start stream: Unknown error...
2020-04-00 22:17:03 [INFO][CURL] Request:
https://10.1.14.88:47984/applist?uniqueid=0123456789ABCDEF
2020-04-00 22:17:04 [INFO][CURL] Response: Ok
2020-04-00 22:17:08 [INFO][CURL] Request:
https://10.1.14.88:47984/serverinfo?uniqueid=0123456789ABCDEF
2020-04-00 22:17:08 [INFO][CURL] Response:
<?xml version="1.0" encoding="UTF-16"?><root protocol_version="0.1" query="serverinfo" status_code="200" status_message="OK"><AuthenticationType>1</AuthenticationType><ConnectionState></ConnectionState><CurrentClient>0</CurrentClient><GfeVersion>3.20.3.63</GfeVersion><GsVersion>gs_04_22_28196077</GsVersion><HttpsPort>47984</HttpsPort><LocalIP>10.1.14.88</LocalIP><LocalIPs><Address>10.1.14.88</Address></LocalIPs><LoginState>2</LoginState><MaxLumaPixelsH264>1721324928</MaxLumaPixelsH264><MaxLumaPixelsHEVC>1869449984</MaxLumaPixelsHEVC><Mode>0</Mode><PairStatus>1</PairStatus><ServerCapability>3895</ServerCapability><ServerCodecModeSupport>3843</ServerCodecModeSupport><ServerColorSpaceSupport>2</ServerColorSpaceSupport><SupportedDisplayMode><DisplayMode><Height>2160</Height><RefreshRate>60</RefreshRate><Width>3840</Width></DisplayMode><DisplayMode><Height>2160</Height><RefreshRate>30</RefreshRate><Width>3840</Width></DisplayMode><DisplayMode><Height>1080</Height><RefreshRate>30</RefreshRate><Width>1920</Width></DisplayMode><DisplayMode><Height>720</Height><RefreshRate>30</RefreshRate><Width>1280</Width></DisplayMode></SupportedDisplayMode><accountId>0A2357BA21F9FA2784BD7EDCA87CA0F35F4B25237483DC609BAB4190AABCB447</accountId><appversion>7.1.422.0</appversion><currentgame>0</currentgame><gamelistid>66082427b583fc7294d025914498d3b6</gamelistid><gputype>GeForce RTX 2080</gputype><hostname>PC-REGIS</hostname><mac>00:D8:61:53:00:8F</mac><numofapps>0</numofapps><resyncSuccessful>0</resyncSuccessful><state>MJOLNIR_STATE_SERVER_AVAILABLE</state><uniqueid>3dea3d5b-3c1f-4986-9854-e5c9762321dc</uniqueid></root>
2020-04-00 22:17:10 [INFO][CURL] Request:
https://10.1.14.88:47984/serverinfo?uniqueid=0123456789ABCDEF
2020-04-00 22:17:10 [INFO][CURL] Response:
<?xml version="1.0" encoding="UTF-16"?><root protocol_version="0.1" query="serverinfo" status_code="200" status_message="OK"><AuthenticationType>1</AuthenticationType><ConnectionState></ConnectionState><CurrentClient>0</CurrentClient><GfeVersion>3.20.3.63</GfeVersion><GsVersion>gs_04_22_28196077</GsVersion><HttpsPort>47984</HttpsPort><LocalIP>10.1.14.88</LocalIP><LocalIPs><Address>10.1.14.88</Address></LocalIPs><LoginState>2</LoginState><MaxLumaPixelsH264>1721324928</MaxLumaPixelsH264><MaxLumaPixelsHEVC>1869449984</MaxLumaPixelsHEVC><Mode>0</Mode><PairStatus>1</PairStatus><ServerCapability>3895</ServerCapability><ServerCodecModeSupport>3843</ServerCodecModeSupport><ServerColorSpaceSupport>2</ServerColorSpaceSupport><SupportedDisplayMode><DisplayMode><Height>2160</Height><RefreshRate>60</RefreshRate><Width>3840</Width></DisplayMode><DisplayMode><Height>2160</Height><RefreshRate>30</RefreshRate><Width>3840</Width></DisplayMode><DisplayMode><Height>1080</Height><RefreshRate>30</RefreshRate><Width>1920</Width></DisplayMode><DisplayMode><Height>720</Height><RefreshRate>30</RefreshRate><Width>1280</Width></DisplayMode></SupportedDisplayMode><accountId>0A2357BA21F9FA2784BD7EDCA87CA0F35F4B25237483DC609BAB4190AABCB447</accountId><appversion>7.1.422.0</appversion><currentgame>0</currentgame><gamelistid>66082427b583fc7294d025914498d3b6</gamelistid><gputype>GeForce RTX 2080</gputype><hostname>PC-REGIS</hostname><mac>00:D8:61:53:00:8F</mac><numofapps>0</numofapps><resyncSuccessful>0</resyncSuccessful><state>MJOLNIR_STATE_SERVER_AVAILABLE</state><uniqueid>3dea3d5b-3c1f-4986-9854-e5c9762321dc</uniqueid></root>

**Comment by rock88** [comment]
After `applist` request and before start a session should be `launch` request, is so strange - logs not available this request. I check what wrong and why this request was skipped.

**Comment by funregis** [comment]
thanks

**Comment by rock88** [comment]
@funregis, I added few starting stream error handler for check this issues, so please test latest build from GitHub Actions CI - https://github.com/rock88/moonlight-nx/actions/runs/129020642.

**Comment by funregis** [comment]
with this version I have a comprehensible error : 1280x720x60 not supported, then I have set the resolution to 1080p, now it's working, good job!!!!
