### ISSUE TITLE
Adding mouse and keyboard support.

### ISSUE THREAD

**Issue by GitHubJota** [rock88/moonlight-nx#30]
Hello,

Thnx for this amazing homebrew app port. For my understanding switch now have native keyboard and mouse support, it only needs to be added by application. This can be huge because it can make possible new genres of games to be playable via streaming on switch.

Best rewards, J.

**Comment by rock88** [comment]
Hi! I added basic USB mouse support, please check [this](https://github.com/rock88/moonlight-nx/actions/runs/545616434) build.
For best keyboard and mouse support needs integrate it directly to glfw or nanogui, I will do it soon.

**Comment by rock88** [comment]
Done, will be available in the next release 🎉

**Comment by rock88** [comment]
Done in [release 1.2.0](https://github.com/rock88/moonlight-nx/releases/tag/1.2.0)
