### ISSUE TITLE
It enhances pointer precision

### ISSUE THREAD

**Issue by Yogsoototh** [rock88/moonlight-nx#32]
Whenever I connect to my PC, the "Enhance pointer precision" option gets turned on out of nowhere. Is this issue related to Moonlight or the Nvidia drivers? Well, either way it's been very inconvenient for me. But it's not a major complaint, I can just turn it off each time but I thought I'd let you know.

**Comment by KiralyCraft** [comment]
It's a known issue, see the #releases channel on the Moonlight discord server for an automatic workaround
