### ISSUE TITLE
Frequent Freezes on GFE v3.20.4.14 & Graphics Driver v452.06

### ISSUE THREAD

**Issue by bugreportanon** [rock88/moonlight-nx#34]
Recently updated my drivers and Geforce Experience to the latest version and I'm getting more freezes on moonlight-nx even with the latest version downloaded from the actions tab, it worked more smoothly on the older version of Geforce Experience and older graphic drivers. Hopefully you can look into this cause moonlight-nx seems less stable now.

**Comment by masagrator** [comment]
I'm on the same GFE and drivers and I don't see any difference.

**Comment by bugreportanon** [comment]
Not sure why but the freezes have become more frequent with me having to force close the title redirected game and reopen the hbmenu and starting moonlight-nx again where it resumes working fine.

**Comment by bugreportanon** [comment]
Weird, turning on logs seems to have fixed this issue.

**Comment by masagrator** [comment]
Yeah, from experience logs can for some reason sometimes impact stability. Disabling SaltyNX logging before refactoring code was making sysmodule unstable...

**Comment by falcorr** [comment]
Logs can introduce a race condition.
