### ISSUE TITLE
Add shift+tab shortcut 

### ISSUE THREAD

**Issue by gagrecco** [rock88/moonlight-nx#36]
Steam big picture is something that really mix well with MoonlightNX, having this shortcut could improve quality of life because to change game it will not longe be necessary to close steam, change to 1080 open steam, change to 720 and the. Chose game. Sometimes the app then crashes and sometimes it works flawlessly. Being able to just exit game without closing steam would be something perfect

**Comment by rock88** [comment]
Done, will be available in the next release 🎉

**Comment by rock88** [comment]
Done in [release 1.2.0](https://github.com/rock88/moonlight-nx/releases/tag/1.2.0)
