### ISSUE TITLE
Render stats button combo doesn't need ZR held

### ISSUE THREAD

**Issue by falcorr** [rock88/moonlight-nx#38]
i.e. ZL+L / ZL + R performs the action.

**Comment by rock88** [comment]
I think it fixed in [this commit](https://github.com/rock88/moonlight-nx/commit/d24560b56dbc4137e6b342e34cf52e41ca298cb5), so latest [release 1.2.0](https://github.com/rock88/moonlight-nx/releases/tag/1.2.0) should include this fix. Please reopen if bug appear in 1.2.0.
