### ISSUE TITLE
Controls remapping

### ISSUE THREAD

**Issue by lildevilx** [rock88/moonlight-nx#4]
Is it possible to remap the preset controls?

I already have a bunch of those combations setup for different commands. And it's causing some issues with my setup already. Would it be possible to change those combo via settings or something?

Thanks!

**Comment by rock88** [comment]
What you mean by preset controls? If it's key combo like Z+L+Down, so I think it possible to add some configuration settings screen for create/remap combo keys (or just some text configuration file).
Also (in future) I want to add a virtual keyboard with full keyboard keys.

**Comment by lildevilx** [comment]
So currently, I'm using zl+zr+left/right, l and r as different things already. So it just kinda causes issues on my games

A text config sounds good too~ or maybe customizable profiles?

**Comment by rock88** [comment]
I added fully customise gamepad buttons/combo key feature, check latest build from [here](https://github.com/rock88/moonlight-nx/actions?query=workflow%3ABuild).
