### ISSUE TITLE
Allow full keyboard access when adding host

### ISSUE THREAD

**Issue by Conanap** [rock88/moonlight-nx#45]
Hello! I have a DDNS set up so I can put in a proper URL and the public IP will be automatically updated. Could you allow us to entre all characters (and therefore URLs) as well? Thanks!

**Comment by rock88** [comment]
Hi! You can try [this](https://github.com/rock88/moonlight-nx/issues/19#issuecomment-665560829) workaround, onscreen keyboard or USB keyboard input in my plans, but not be soon.

**Comment by Conanap** [comment]
Hi! Apologies for the late reply. Thanks for the insight! That seems like a fair solution.

**Comment by Conanap** [comment]
closed for duplicate
