### ISSUE TITLE
GeForce Experience 3.22 incompatibility

### ISSUE THREAD

**Issue by cgutman** [rock88/moonlight-nx#59]
In order to support streaming with GFE 3.22 (which was officially released a few days ago), you'll need to update moonlight-common-c to the latest upstream code.

It looks like some users are starting to run into that issue - https://gbatemp.net/threads/moonlight-nx-nvidia-game-stream-client.565903/page-13

**Comment by AlexKuai** [comment]
The latest version of GeForce Experience (I'm on 3.22.0.32) seems to break Moonlight-NX. All I'm getting when I try to connect is "Failed to start stream"

**Comment by rock88** [comment]
Done 👌
