### ISSUE TITLE
Problem with the local ssl certificate in switch

### ISSUE THREAD

**Issue by oualich** [rock88/moonlight-nx#6]
Hello, I Have a problem on the pairing between the pc and moonlight.
anyone have a solution to offer me?

**Comment by lildevilx** [comment]
Does it work on computers or android/ios?

**Comment by rock88** [comment]
Hi, you use nro from release page or compile by yourself? This error has happened for me when I used newest libcurl (7.69.2), with previous libcurl (7.69.1) all fine. 
Also your certs may be corrupted for some reasons, try to delete a `key` folder from sdcard/moonlight and try again.

**Comment by oualich** [comment]
android it works well
Currently my switch is under sx os, it detects my pc. it's just after entering the code i have the error.
Currently I put the nro file directly at the root of the sd card and as well as on sdcard / switch / moonlight
and besides it create a json fact of id.

**Comment by oualich** [comment]
Problem resolve, basic fact my hbmenu is empty  because the sd card is in exfat :
suddenly I had to change the permissions of my switch folder
https://gbatemp.net/threads/how-to-fix-sd-reading-problems-for-macos-users.510856/
