### ISSUE TITLE
Grey Screen Fix and Suggestion to be able to swap X and Y keys as well.

### ISSUE THREAD

**Issue by kodithegreat** [rock88/moonlight-nx#7]
Every time I tried to stream any game I was faced with a grey/black screen but the audio was there.
To fix this I updated my switch firmware and CFW.

Grey screen builds:
Switch Firmware 10.0.0
Atmosphere: 0.9.0

Working flawlessly on:
Switch Firmware: 10.0.3
Atmosphere: 0.12.0

**Comment by rock88** [comment]
Yep, I thinking to add some info in Main screen for suggest to user for use 5GHz WiFi instead of 2.4 for better performance (2.4 GHz WiFi very badly work for me), also I add info about firmware and atmo version!
Also I think add feature for support a full buttons remapping (and key combos) instead of some specific button.

**Comment by kodithegreat** [comment]
> Yep, I thinking to add some info in Main screen for suggest to user for use 5GHz WiFi instead of 2.4 for better performance (2.4 GHz WiFi very badly work for me), also I add info about firmware and atmo version!

Great idea!!

> Also I think add feature for support a full buttons remapping (and key combos) instead of some specific button.

This would be amazing and push my rating to 5/5.
Would you be able to make a hotfix to swap x/y individually as well as b/a?
Doing this would temporarily fix the mismatch of inputs between the switch and the 360 controller my PC recognises the switch as. 
It's a small but annoying issue as I cannot remap controls via steam controller config with the switch.
I really appreciate your work!

**Comment by rock88** [comment]
In the latest [build](https://github.com/rock88/moonlight-nx/actions?query=workflow%3ABuild) I added fully gamepad buttons/combo keys remapping feature, check that)
